Refactored the scss for the alerts.
plone/plonetheme.barceloneta pull request #250
Opened 2021-09-09 09:20 UTC by klje

2021-09-09 09:20 UTC, mister-roboto commented
@klje thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-09-09 09:57 UTC, klje commented
@jenkins-plone-org please run jobs

2021-09-09 12:13 UTC, MrTango approved these changes
LGTM, please do a rebase from master to fix the conflicts with the compiled css files and merge the PR.

2021-09-09 12:13 UTC, MrTango commented on scss/alerts.scss
> +}
this might work, but i still think it would be better to wrap the whole definitions in one .alert{} block ;)

2021-09-14 07:14 UTC, jensens commented
> LGTM, please do a rebase from master to fix the conflicts with the compiled css files and merge the PR.

@klje with a PR in this package, it is better to no include the compiled changes, but only the SCSS - otherwise its gets annoying for you.

2021-09-14 07:30 UTC, agitator requested changes
Please read the comments in https://github.com/plone/plonetheme.barceloneta/pull/245#issuecomment-899677498

2021-09-30 07:10 UTC, mister-roboto commented
@InteraktivMeis you need to sign the Plone Contributor Agreement in order to merge this pull request. 

Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

2021-09-30 09:48 UTC, mister-roboto commented
@InteraktivMeis you need to sign the Plone Contributor Agreement in order to merge this pull request. 

Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

2021-11-04 08:40 UTC, mister-roboto commented
@InteraktivMeis you need to sign the Plone Contributor Agreement in order to merge this pull request. 

Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

2021-11-04 14:56 UTC, merged