Bootstrap 5.3.0 alpha2 integration
plone/plonetheme.barceloneta pull request #324
Opened 2023-03-30 09:42 UTC by toalba

added the new bootstrap 5.3.0-alpha2

2023-03-30 10:02 UTC, toalba commented
Change-log: https://blog.getbootstrap.com/2023/03/24/bootstrap-5-3-0-alpha2/

2023-03-30 12:09 UTC, petschki requested changes
additionally i recomment to make a `npm upgrade` to get the latest versions of the dependencies.

2023-03-30 12:09 UTC, petschki commented on news/324.feature
> +Added Bootstrap 5.3.0-alpha2 and tested the changes.
```suggestion
Update to Bootstrap 5.3.0-alpha2.
```

2023-03-30 12:09 UTC, petschki commented on plonetheme/barceloneta/theme/css/barceloneta.css
Something went wrong here. @toalba compiled to alpha2 but  @lenadax compiled back to alpha1... please take a look again.

2023-03-31 06:31 UTC, lenadax commented on plonetheme/barceloneta/theme/css/barceloneta.css
@petschki Apologies, I think a lockfile messed with me. I recompiled the css with bootstrap-5.3.0-alpha2 now.

2023-03-31 06:36 UTC, petschki commented on plonetheme/barceloneta/theme/css/barceloneta.css
No worries ... now it looks good 👍🏼

2023-03-31 06:37 UTC, petschki approved these changes

2023-03-31 06:40 UTC, merged