Add styles for details/summary based collapsibles.
plone/plonetheme.barceloneta pull request #374
Opened 2024-06-16 12:08 UTC by thet

Add styles for details/summary based collapsibles.

Ref: https://github.com/plone/Products.CMFPlone/pull/3976

2024-06-16 12:08 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-06-17 11:21 UTC, petschki requested changes

2024-06-17 14:48 UTC, thet commented on plonetheme/barceloneta/theme/tinymce/tinymce-ui-content.css
no, not the tinymce ones. I just ran `yarn build` and that was also generated.
I have it removed!

2024-06-17 15:49 UTC, petschki approved these changes
👍

2024-06-19 10:49 UTC, merged